name: 'YAML File Scanner'
description: 'Iterates over all files in a repository and posts YAML file contents to an HTTP endpoint'
inputs:
  scanner_api_url:
    description: 'The API URL of your Scanner instance'
    required: true
  scanner_api_key:
    description: 'Scanner API key'
    required: true
  file:
    description: 'Detection rule file(s) - comma separated list of .yml or .yaml files'
    required: false
  dir:
    description: 'Directory of detection rule files'
    required: false
  recursive:
    description: 'Recursively search directory for valid YAML files'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Install scanner-cli
      shell: bash
      run: pip install --quiet scanner-cli
    - name: Run validation
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        INPUT_SCANNER_API_URL: ${{ inputs.scanner_api_url }}
        INPUT_SCANNER_API_KEY: ${{ inputs.scanner_api_key }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_DIR: ${{ inputs.dir }}
        INPUT_RECURSIVE: ${{ inputs.recursive }}
branding:
  icon: 'file-text'
  color: 'blue'