#!/bin/bash
# Regenerates the `gen/*.ts` schema bundles from the JSON schemas published in
# scanner-inc/scanner-cli. Run via `yarn gen_schema`.
#
# Requires the `gh` CLI (https://cli.github.com/) to be installed and
# authenticated against an account with read access to the repo.
#
# Override the source ref via $SCANNER_CLI_REF. Default tracks the in-flight
# branch; switch to `main` once that branch merges.
set -euo pipefail

REPO="scanner-inc/scanner-cli"
REF="${SCANNER_CLI_REF:-swwu/commit-msg-and-json}"
SCHEMAS=(
  "validate-result"
  "run-tests-result"
)

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "$repo_root/gen"

# Single per-run tmp dir + single trap → no orphaned partial files on error.
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

cd "$repo_root"

for name in "${SCHEMAS[@]}"; do
  schema_path="schemas/$name.schema.json"
  # Derive a predictable output filename from the schema slug, e.g.
  # `validate-result` → `gen/validate_result.ts`.
  dst="$repo_root/gen/${name//-/_}.ts"
  schema_tmp="$tmp_dir/$name.schema.json"
  ts_tmp="$tmp_dir/$name.ts"

  echo "Downloading $REPO/$schema_path @ $REF ..."
  gh api \
    -H "Accept: application/vnd.github.raw" \
    "/repos/$REPO/contents/$schema_path?ref=$REF" \
    > "$schema_tmp"

  # `--no-additionalProperties` strips the catch-all `[k: string]: unknown;`
  # that json-schema-to-typescript otherwise tacks on every interface — those
  # index signatures make downstream type checking useless.
  yarn run --silent json2ts \
    --input "$schema_tmp" \
    --no-additionalProperties \
    > "$ts_tmp"

  {
    echo "// AUTOGENERATED — regenerate via \`yarn gen_schema\` (sources the"
    echo "// schema from scanner-inc/scanner-cli)."
    echo ""
    cat "$ts_tmp"
  } > "$dst"

  echo "Wrote $dst"
done
