name: Test Detection Rule Validator using dir

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Test the action
        uses: ./
        with:
          scanner_api_url: '${{ secrets.SCANNER_API_URL }}'
          scanner_api_key: '${{ secrets.SCANNER_API_KEY }}'
          dir: 'tests'
          recursive: true
